### ISSUE TITLE
OOTA support

### ISSUE THREAD

**Issue by JoooostB** [adafruit/Adafruit_CircuitPython_TinyLoRa#32]
I got this project working very reliable, which I'm very thankful for. However, I'm in an unfortunate position that TTN does not cover the location where I'd like to deploy one of my sensors. This means I'm obligated to use a nationwide LoRa network offered by our national telecom provider KPN. Although unfortunate, this doesn't bother me too much. Anyway, this does imply that I'd need to Identify using OOTA, instead of ABP [(as documented here)](https://docs.kpnthings.com/lora/technical-information/device-identification). As the latter is not supported by KPN due to it being (and I quote) _"not secure enough"_.

What are the chances you'll be implementing OOTA support in this Library? If you could guide me in the right direction I may be able to contribute (if desirable).

Kind regards.

**Comment by brentru** [comment]
> What are the chances you'll be implementing OOTA support in this Library? 

Hi @JoooostB  - I have no current plans to convert this library from ABP to OOTA and haven't spent time digging into what would be specifically involved.

> If you could guide me in the right direction I may be able to contribute (if desirable).

You may want to look at MCCI's LMIC library for Arduino, it's capable of performing OOTA. 

https://github.com/mcci-catena/arduino-lorawan
