### ISSUE TITLE
Clarify LICENSE

### ISSUE THREAD

**Issue by tykling** [adafruit/Adafruit_CircuitPython_TinyLoRa#38]
Hello,

LICENSE file says MIT, LICENSES folder has several, and README says LGPL. Which is it? :)

Thanks

**Comment by tannewt** [comment]
I'd go based on the license listed in each file: https://github.com/adafruit/Adafruit_CircuitPython_TinyLoRa/blob/master/adafruit_tinylora/adafruit_tinylora.py#L3

**Comment by brentru** [comment]
^ what @tannewt  said - the overall `tinylora` (adafruit_tinylora.py) implementation is LGPL (Ideetron B.V.).
