### ISSUE TITLE
OTAA progress

### ISSUE THREAD

**Issue by bsimmo** [adafruit/Adafruit_CircuitPython_TinyLoRa#40]
Is there any progress on OTAA support, the upcoming TTNv3 migration this year is really pushing for OTAA usage.

**Comment by brentru** [comment]
No updates as of now, we'd love if someone from the community or TTN would be able to assist. 

Closing in favor of moving all OTAA/TTNv3/Downlink discussion to one issue: https://github.com/adafruit/Adafruit_CircuitPython_TinyLoRa/issues/37
