### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by bsimmo** [adafruit/Adafruit_CircuitPython_TinyLoRa#41]
There doesn't seem to be an API for this, just an example of usage.

**Comment by ladyada** [comment]
https://circuitpython.readthedocs.io/projects/tinylora/en/latest/

**Comment by bsimmo** [comment]
Yes I know that but there is nothing under the API link there.
https://circuitpython.readthedocs.io/projects/tinylora/en/latest/api.html

**Comment by jposada202020** [comment]
@bsimmo Thanks, this will be corrected by #43 :). maybe next time a PR to solve this will help.

**Comment by ladyada** [comment]
thanks @jposada202020 !

**Comment by jposada202020** [comment]
:)
