### ISSUE TITLE
TTN V3

### ISSUE THREAD

**Issue by bsimmo** [adafruit/Adafruit_CircuitPython_TinyLoRa#42]
We're looking to migrate out TTN gateways to v3 as and when needed, so we need to look at using V3 in our code.
This looks to still be at v2.   What's the status, if any, on planned TTN v3 compatibility.
If it's none, that's fine, just nice to know.

**Comment by ladyada** [comment]
this is a dup of
https://github.com/adafruit/Adafruit_CircuitPython_TinyLoRa/issues/37
?
we'd love to have the community or TTN help with V3 implementation!

**Comment by bsimmo** [comment]
Ah, that is just titled downlink not v3. 

Hope someone that knows how to can fix it :-)
