### ISSUE TITLE
TinyLora Receive?

### ISSUE THREAD

**Issue by PeteHollyer** [adafruit/Adafruit_CircuitPython_TinyLoRa#44]
I need to Send and Receive from one Radio to a Second Radio not an online network.  I can NOT find a Receive Example on the TinyLora Library.
Is there Anyway I can receive an Example code?

Pete

**Comment by jerryneedell** [comment]
TinyLoRa does not receive -- it is for transmitting to The Things Network (LORAWAN).
To communicate between two radios use the Adafruit CircuitPython RFM9x library.
https://github.com/adafruit/Adafruit_CircuitPython_RFM9x
