### ISSUE TITLE
Missing Type Annotations

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_TinyLoRa#45]
There are missing type annotations for some functions in this library.

The `typing` module does not exist on CircuitPython devices so the import needs to be wrapped in try/except to catch the error for missing import. There is an example of how that is done here:

```python
try:
    from typing import List, Tuple
except ImportError:
    pass
```

Once imported the typing annotations for the argument type(s), and return type(s) can be added to the function signature. Here is an example of a function that has had this done already:

```python
def wrap_text_to_pixels(
    string: str, max_width: int, font=None, indent0: str = "", indent1: str = ""
) -> List[str]:
```
If you are new to Git or Github we have a guide about contributing to our projects here: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

There is also a guide that covers our CI utilities and how to run them locally to ensure they will pass in Github Actions here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code In particular the pages: `Sharing docs on ReadTheDocs` and `Check your code with pre-commit` contain the tools to install and commands to run locally to run the checks.

If you are attempting to resolve this issue and need help, you can post a comment on this issue and tag both @foamyguy and @kattni or reach out to us on Discord: https://adafru.it/discord in the `#circuitpython-dev` channel.

The following locations are reported by mypy to be missing type annotations:

- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:14
- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:46
- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:52
- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:59
- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:106
- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:137
- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:149
- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:178
- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:188
- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:197
- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:206
- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:217
- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:225
- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:248
- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:326
- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:347
- [ ] adafruit_tinylora/adafruit_tinylora_encryption.py:361
- [ ] adafruit_tinylora/adafruit_tinylora.py:73
- [ ] adafruit_tinylora/adafruit_tinylora.py:114
- [ ] adafruit_tinylora/adafruit_tinylora.py:207
- [ ] adafruit_tinylora/adafruit_tinylora.py:223
- [ ] adafruit_tinylora/adafruit_tinylora.py:269
- [ ] adafruit_tinylora/adafruit_tinylora.py:315
- [ ] adafruit_tinylora/adafruit_tinylora.py:333
- [ ] adafruit_tinylora/adafruit_tinylora.py:339
- [ ] adafruit_tinylora/adafruit_tinylora.py:356
- [ ] adafruit_tinylora/adafruit_tinylora.py:363

**Comment by samatjain** [comment]
Working on this as part of PyCon 2023 sprints.
