### ISSUE TITLE
Receive example

### ISSUE THREAD

**Issue by jwktje** [adafruit/Adafruit_CircuitPython_TinyLoRa#7]
Super excited about this library. Is there an example of a downlink with this library?

Or alternatively, what functions should I use for this? That way I can test and submit a PR with a working example. 

Alternatively I was also wondering if this library would work with something like LoraServer or is it only for TTN?

**Comment by brentru** [comment]
> Super excited about this library. Is there an example of a downlink with this library? Or alternatively, what functions should I use for this? That way I can test and submit a PR with a working example.

Thanks! Only uplink is currently implemented. 

> Alternatively I was also wondering if this library would work with something like LoraServer or is it only for TTN?

It's currently configured for TTN. I haven't tried loraserver, but the regional frequency files (see: https://github.com/adafruit/Adafruit_CircuitPython_TinyLoRa/blob/master/adafruit_tinylora/ttn_usa.py) are the only TTN-specific data in this library.

**Comment by jwktje** [comment]
That makes sense.
Do you happen to know if there is anything that is TTN specific apart from those frequencies? Otherwise I'd imagina that any Gateway following the LoraWan spec should work fine with this, no?

Are there plans to implement Downlink?

**Comment by brentru** [comment]
> Do you happen to know if there is anything that is TTN specific apart from those frequencies? 

Otherwise I'd imagina that any Gateway following the LoraWan spec should work fine with this, no?
That's the only TTN-specific part of this library, it should work with any gateway following the LoRaWAN spec. 


> Are there plans to implement Downlink?

It's not on my immediate radar, but it would be a nice feature to have.

**Comment by rboulle** [comment]
Yes definitely, that would be great.

There is a full LoRaWAN stack here : https://github.com/jeroennijhof/LoRaWAN

I am too new to circuitpython to know if it can be used in a more or less straightforward way.
