### ISSUE TITLE
ttn_AU.py incorrect

### ISSUE THREAD

**Issue by philwilkinson40** [adafruit/Adafruit_CircuitPython_TinyLoRa#8]
Either the comment or the actual dictionary values in ttn_AU.py file are incorrect.
  ttn  https://github.com/TheThingsNetwork/gateway-conf/blob/master/AU-global_conf.json indicates the first channel in AU915 is 916.8MHz. 
Sorry I couldnt just submit a pull,  unfortunately I have no idea how you have converted lsb, mid, msb into the frequency value!

**Comment by brentru** [comment]
HI @philwilkinson40. This is a pythonified-port of TinyLoRa. I was following the conversion from TinyLoRa. The conversions are found on the main repo: https://github.com/adafruit/TinyLoRa/blob/master/TinyLoRa.cpp#L63.
